--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/David-pm-pl/iLand
build-by-default: true
branches:
- stable
projects:
  iLand:
    path: ""
    icon: "assets/images/icon.png"
    libs:
     - src: davidglitch04/libEco/libEco
       version: ^3.0.0
       branch: stable
    lint:
      phpstan: false
...
