--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/David-pm-pl/iLand
build-by-default: true
branches:
- stable
projects:
  iLand:
    path: ""
    icon: "assets/images/icon.png"
    libs:
      - src: David-pm-pl/libEco/libEco
        version: ^3.0.0
        branch: stable
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.1.2
    lint:
      phpstan: false
...
