name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-php:
    name: Prepare PHP
    runs-on: ${{ matrix.image }}

    strategy:
      matrix:
        image: [ubuntu-20.04]
        php: [8.0.18]

    steps:
      - name: Build and prepare PHP cache
        uses: pmmp/setup-php-action@aa636a4fe0c1c035fd9a3f05e360eadd86e06440
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"
          
  codestyle:
    name: Code Style checks
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP and tools
        uses: shivammathur/setup-php@2.15.0
        with:
          php-version: 8.0
          tools: php-cs-fixer:3.2

      - name: Run PHP-CS-Fixer
        run: php-cs-fixer fix --dry-run --diff --ansi
